# Behavioral checks on temporary fixtures; no study inputs are changed.
source_repo <- normalizePath(Sys.getenv("SLC7A5_REPO_ROOT", unset = getwd()))
fixture <- tempfile("slc-path-tests-")
dir.create(file.path(fixture, "config"), recursive = TRUE)
dir.create(file.path(fixture, "R"))
file.copy(file.path(source_repo, "R", "paths.R"), file.path(fixture, "R", "paths.R"))
file.copy(file.path(source_repo, "config", "bulk_samples.tsv"), file.path(fixture, "config", "bulk_samples.tsv"))
writeLines('{"data_root":"data","seed":42,"input_overrides":{}}', file.path(fixture, "config", "paths.json"))
writeLines('{"example":{"path":"cohort/value.txt","generated":true}}', file.path(fixture, "config", "inputs.json"))
Sys.setenv(SLC7A5_REPO_ROOT = fixture)
Sys.unsetenv("SLC7A5_DATA_ROOT")
source(file.path(fixture, "R", "paths.R"))
fails <- function(expr) inherits(tryCatch(force(expr), error = identity), "error")
stopifnot(fails(slc_input("example")), !dir.exists(file.path(fixture, "results")))
dir.create(file.path(fixture, "data", "cohort"), recursive = TRUE)
original <- file.path(fixture, "data", "cohort", "value.txt")
writeLines("original", original)
stopifnot(identical(readLines(slc_input("example")), "original"))
output <- slc_output("cohort/value.txt")
writeLines("new result", output)
stopifnot(identical(readLines(original), "original"), identical(slc_input("example"), output))
slc_config$input_overrides <- list(example = original)
stopifnot(identical(slc_input("example"), original))
stopifnot(fails(slc_output("../outside.txt")), fails(slc_output("/tmp/outside.txt")))
ordered <- c("siSLC_LPS5-2", "siCon_3", "siCon_LPS_1")
info <- slc_sample_info(ordered)
stopifnot(identical(rownames(info), ordered),
          identical(as.character(info$group), c("siSLC_LPS5", "siCon", "siCon_LPS")),
          fails(slc_sample_info(c("unknown"))), fails(slc_sample_info(c("siCon_1", "siCon_1"))))
if (.Platform$OS.type == "unix") {
  file.symlink(original, file.path(fixture, "results", "alias.txt"))
  stopifnot(fails(slc_output("alias.txt")))
  file.symlink(file.path(fixture, "data"), file.path(fixture, "results", "alias"))
  stopifnot(fails(slc_output("alias/new/file.txt")), !dir.exists(file.path(fixture, "data", "new")))
}
unlink(fixture, recursive = TRUE)
cat("R path isolation and sample mapping: PASS\n")
